-- Insert Real Employees
-- This script inserts all employee names into the employees table

INSERT INTO employees (first_name, last_name, is_active)
VALUES
('Omar', 'Abdullahi', TRUE),
('Kevin', 'Aldana', TRUE),
('Daniel', 'Anderson', TRUE),
('Kwasi', 'Baal-Gyimah', TRUE),
('Junior', 'Bantoe', TRUE),
('Janyla', 'Cross', TRUE),
('Dominic', 'Davis', TRUE),
('Jeasyne', 'Dekoster', TRUE),
('Menhem', 'El Ashkar', TRUE),
('Allen', 'Hang', TRUE),
('Pouapheng', 'Her', TRUE),
('John', 'Htoo', TRUE),
('Eric', 'Jones', TRUE),
('Maxwell', 'Kangas', TRUE),
('Issac', 'Kennedy', TRUE),
('Phillip', 'Kishchun', TRUE),
('Tara', 'LaLonde', TRUE),
('Jeffery', 'Lee', TRUE),
('Kevin', 'Lee', TRUE),
('Lucy', 'Lee', TRUE),
('Soomboom', 'Lee', TRUE),
('Xai', 'Lor', TRUE),
('Arif', 'Mohamed', TRUE),
('Chang', 'Moua', TRUE),
('Ronald', 'Murph', TRUE),
('Ernest', 'Ngoran', TRUE),
('Thomond', 'Obrien', TRUE),
('Liban', 'Omar-samatar', TRUE),
('Terrance', 'Peaches', TRUE),
('Jose', 'Reyes', TRUE),
('Darrien', 'Scarver', TRUE),
('Oshawna', 'Searight-Peyton', TRUE),
('Rolmen', 'Sparkman', TRUE),
('Chamee', 'Thao', TRUE),
('Chee', 'Thao', TRUE),
('Ger', 'Thao', TRUE),
('Kaolee', 'Thao', TRUE),
('Ntxhais', 'Thao', TRUE),
('Yang', 'Thao', TRUE),
('A', 'Vang', TRUE),
('Anthony', 'Vang', TRUE),
('Ger', 'Vang', TRUE),
('Harry', 'Vang', TRUE),
('Isaac', 'Vang', TRUE),
('Joshua', 'Vang', TRUE),
('Kong', 'Vang', TRUE),
('Laly', 'Vang', TRUE),
('Sai', 'Vang', TRUE),
('Tong', 'Vang', TRUE),
('Yeej Pheej', 'Vue', TRUE),
('Frank', 'William', TRUE),
('Hayley', 'Williams', TRUE),
('Samdi', 'Williams', TRUE),
('Yuge', 'Xiong', TRUE),
('Kang', 'Yang', TRUE),
('Mai', 'Yang', TRUE),
('Mai', 'Yang', TRUE),
('Mong', 'Yang', TRUE);

-- Verify the inserted employees
-- SELECT COUNT(*) as total_employees FROM employees;
-- SELECT * FROM employees ORDER BY first_name, last_name;

